### PR TITLE
Fix linux

### PR DESCRIPTION
**Pull request by uAliFurkanY**
- Move GCC.cmake to GNU.cmake
- Fix build instructions for Linux
- Add dependency list

### CODE REVIEW

**Comment by tree786isback** [comment]
I've tried compiling the branch with these changes on an arch distro, but I get some cmake errors like these:
```
CMake Error at CMakeLists.txt:29 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//PlasmaGit.cmake


CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//PlasmaVersion.cmake


CMake Error at CMakeLists.txt:31 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//PlasmaPlatform.cmake


CMake Error at CMakeLists.txt:38 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//PlasmaFunctions.cmake


CMake Error at CMakeLists.txt:41 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//Toolchain//GNU.cmake


CMake Error at CMakeLists.txt:44 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//CMakeFlags.cmake


CMake Error at CMakeLists.txt:46 (add_subdirectory):
  The source directory

    /home/..../Desktop/PlasmaEngine/Source/Platform

  does not contain a CMakeLists.txt file.


```

**Comment by dragonCASTjosh** [comment]
@tree786isback the latest linux changes should already be in the master branch. i recommend you try that and report back

**Comment by tree786isback** [comment]
Ah thanks. I've downloaded the latest branch and tried to compile now, but I get a different error this time:
```
CMake Error at CMakeFiles/Toolchain/GNU.cmake:54:
  Parse error.  Expected a command name, got right paren with text ")".
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)

```
I'm on an arch based distro, and using GCC/++ 11 to compile. Any ideas on how to fix this?

**Comment by dragonCASTjosh** [comment]
are you sure your using the Master branch, because GNU.cmake doesnt exist on master it uses GCC.cmake

**Comment by tree786isback** [comment]
I cloned the main branch and checkout the latest [commit](https://github.com/PlasmaEngine/PlasmaEngine/commit/9dda0a72a91b9694a28d707ccc51f90f4076d884), still getting an error but it looks a bit different to the previous one:
```
CMake Error at CMakeLists.txt:41 (include):
  include could not find requested file:

    /home/..../Desktop/PlasmaEngine/CMakeFiles//Toolchain//GNU.cmake


CMake Error at CMakeFiles/PlasmaFunctions.cmake:7 (plasma_toolchain_setup_library):
  Unknown CMake command "plasma_toolchain_setup_library".
Call Stack (most recent call first):
  Source/Platform/Linux/CMakeLists.txt:3 (plasma_setup_library)

```
Not sure if I'm doing something wrong with my setup?

**Comment by dragonCASTjosh** [comment]
hmm, Can you make a copy of the gcc file and rename it to gnu

**Comment by tree786isback** [comment]
Ah cheers , renaming it to GNU fixed it. But I'm now getting some compile errors. Might be better if I open a thread in the discussions sections.

**Comment by dragonCASTjosh** [comment]
Try the feature/linux branch
also if it fails create an issue report we can continue it there

**Pull request closed without merging**
