### PR TITLE
GCC/Linux fixups

### PR DESCRIPTION
**Pull request by openglfreak**
not complete

### CODE REVIEW

**Comment by openglfreak** [comment]
https://github.com/assimp/assimp/commit/6ebae5e67c49097b1c55a51f4ead053bc33d8255
https://github.com/castano/nvidia-texture-tools/commit/6474f2593428d89ec152da2502aa136ababe66ca
and a SpirvTools update are needed too

**Comment by dragonCASTjosh** [comment]
@openglfreak have you tested updating the 3rd parties? are they just plugin and play updates? if so i can do that to main today

**Comment by uAliFurkanY** [comment]
Your GNU.cmake hardlink is broken

**Comment by dragonCASTjosh** [comment]
Manually merged changes into a new branch 
https://github.com/PlasmaEngine/PlasmaEngine/tree/feature/Linux

**Pull request closed without merging**
